# Generated by Django 4.1.3 on 2023-01-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogery',
            field=models.CharField(choices=[('SH', 'shoes'), ('KU', 'kurta'), ('TW', 'topware'), ('BW', 'bottomware')], max_length=10),
        ),
    ]
