# Generated by Django 4.1.3 on 2023-02-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_catogery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catogery',
            field=models.CharField(choices=[('SH', 'shoes'), ('KU', 'kurta'), ('TW', 'topware'), ('BW', 'bottomware'), ('SR', 'saree')], max_length=10),
        ),
    ]
